src/InteractiveValley/BackendBundle/Entity/Usuario.php
<?php

namespace InteractiveValley\BackendBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;


/**
 * Usuario
 *
 * @ORM\Table(name="usuarios")
 * @ORM\Entity(repositoryClass="InteractiveValley\BackendBundle\Repository\UsuarioRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity("email")
 */
class Usuario implements UserInterface, \Serializable
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank(message="Ingresa tu nombre")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255)
     * @Assert\Email(message="Email invalido")
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="salt", type="string", length=255)
     */
    private $salt;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @var integer
     *
     * @ORM\Column(name="type", type="integer")
     */
    private $type;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_active", type="boolean", nullable=true)
     */
    private $isActive;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @var PublicacionesBundle:Publicacion
     *
     * @ORM\OneToMany(targetEntity="InteractiveValley\PublicacionesBundle\Entity\Publicacion",mappedBy="author",cascade={"remove"})
     * @ORM\OrderBy({"title" = "ASC"})
     */
    private $publications;
    
    const GROUP_USERS    =   1;
    const GROUP_ADMIN       =   2;
    const GROUP_SUPER_ADMIN =   3;
    
    public function __toString(){
        return $this->getName();
    }
    
    public function getStringCompleto(){
        return $this->getName();
    }
    
    public function getStringTypeGroup(){
        $arreglo=array(
            self::GROUP_ADMIN=>'Administrador',
            self::GROUP_SUPER_ADMIN=>'Superadmin',
        );
        return $arreglo[$this->getType()];
    }
    
    static function getArrayTypeGroup($is_super_admin=false){
        if($is_super_admin){
            $sTipoGrupo=array(
                self::GROUP_ADMIN=>'Administrador',
                self::GROUP_SUPER_ADMIN=>'Superadmin',
            );
        }else{
            $sTipoGrupo=array(
                self::GROUP_ADMIN=>'Administrador'
            );
        }
        return $sTipoGrupo;
    }
    
    static function getPreferedTypeGroup(){
        return array(self::GROUP_ADMIN);
    }

    
    public function __construct()
    {
        // may not be needed, see section on salt below
        $this->salt = base_convert(sha1(uniqid(mt_rand(), true)), 16, 36);
        $this->isActive = true;
        $this->type = Usuario::GROUP_ADMIN;
    }
    
    /*
     * Timestable
     */
    
    /**
     ** @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        if(!$this->getCreatedAt())
        {
          $this->createdAt = new \DateTime();
        }
        if(!$this->getUpdatedAt())
        {
          $this->updatedAt = new \DateTime();
        }
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTime();
    }
    
    public function eraseCredentials()
    {
    }
    
    public function getRoles() {
        if ($this->getType() == self::GROUP_USERS) {
            return array('ROLE_USER', 'ROLE_API');
        } elseif ($this->getType() == self::GROUP_SUPER_ADMIN) {
            return array('ROLE_SUPER_ADMIN', 'ROLE_API');
        } else {
            return array('ROLE_ADMIN', 'ROLE_API');
        }
    }
    
    /**
     * Get username
     *
     * @return string | email
     */
    public function getUsername()
    {
        return $this->email;
    }


    /*** uploads ***/
    
    /**
     * @Assert\File(maxSize="6000000")
     */
    private $file;

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
        // check if we have an old image path
        if (isset($this->image)) {
            // store the old name to delete after the update
            $this->temp = $this->image;
            $this->image = null;
        } else {
            $this->image = 'initial';
        }
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }
    
    /**
    * @ORM\PrePersist
    * @ORM\PreUpdate
    */
    public function preUpload()
    {
      if (null !== $this->getFile()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->image = $filename.'.'.$this->getFile()->guessExtension();
        }
    }

    /**
    * @ORM\PostPersist
    * @ORM\PostUpdate
    */
    public function upload()
    {
      if (null === $this->getFile()) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move($this->getUploadRootDir(), $this->image);

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            unlink($this->getUploadRootDir().'/'.$this->temp);
            // clear the temp image path
            $this->temp = null;
        }
        $this->file = null;
    }

    /**
    * @ORM\PostRemove
    */
    public function removeUpload()
    {
      if ($file = $this->getAbsolutePath()) {
        if(file_exists($file)){
            unlink($file);
        }
      }
    }
    
    protected function getUploadDir()
    {
        return '/uploads/usuarios';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web'.$this->getUploadDir();
    }
    
    public function getWebPath()
    {
        return null === $this->image ? null : $this->getUploadDir().'/'.$this->image;
    }
    
    public function getAbsolutePath()
    {
        return null === $this->image ? null : $this->getUploadRootDir().'/'.$this->image;
    }
    
    /**
     * @see \Serializable::serialize()
     */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->name,
            $this->email
        ));
    }

    /**
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->name,
            $this->email
        ) = unserialize($serialized);
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Usuario
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Usuario
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return Usuario
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set salt
     *
     * @param string $salt
     * @return Usuario
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;

        return $this;
    }

    /**
     * Get salt
     *
     * @return string 
     */
    public function getSalt()
    {
        return $this->salt;
    }

    /**
     * Set image
     *
     * @param string $image
     * @return Usuario
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string 
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set type
     *
     * @param integer $type
     * @return Usuario
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer 
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return Usuario
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**

src/InteractiveValley/BackendBundle/Form/UsuarioType.php
<?php

namespace InteractiveValley\BackendBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class UsuarioType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name','text',array('label'=>'Nombre','attr'=>array('class'=>'form-control')))
            ->add('email','email',array('attr'=>array('class'=>'form-control')))
            ->add('password', 'repeated', array(
                'type' => 'password',
                'invalid_message' => 'Las dos contraseñas deben coincidir',
                'first_options'   => array('label' => 'Contraseña'),
                'second_options'  => array('label' => 'Repite Contraseña'),
                'required'        => false,
                'options' => array(
                    'attr'=>array('class'=>'form-control placeholder')
                )
            )) 
            ->add('salt','hidden')
            ->add('image','hidden')
            ->add('type','hidden')
            ->add('isActive',null,array('label'=>'Activo?','attr'=>array(
                'class'=>'checkbox-inline',
                'placeholder'=>'Es activo',
                'data-bind'=>'value: isActive'
                )))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'InteractiveValley\BackendBundle\Entity\Usuario'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'interactivevalley_backendbundle_usuario';
    }
}

src/InteractiveValley/BackendBundle/Resources/views/Usuario/edit.html.twig
{% extends 'BackendBundle::layout.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
    <!-- Main stylesheet -->
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <!-- Widgets stylesheet -->
    <link rel="stylesheet" href="{{asset('css/widgets.css')}}">   
    <!-- Gritter Notifications stylesheet -->
    <link rel="stylesheet" href="{{asset('css/jquery.gritter.css')}}">
    <!-- jQuery Validation Engine stylesheet -->
    <link rel="stylesheet" href="{{asset('css/validationEngine.jquery.css')}}">
    <!-- CLEditor -->
    <link rel="stylesheet" href="{{asset('css/jquery.cleditor.css')}}"> 
{% endblock %}

{% block mainbar %}
    <!-- Main bar -->
    <div class="mainbar">

        <!-- Page heading -->
        <div class="page-head">
            <h2 class="pull-left">Usuarios</h2>
            <div class="clearfix"></div>
            <!-- Breadcrumb -->
            <div class="bread-crumb">
                <a href="{{path('backend_homepage')}}"><i class="fa fa-home"></i>Dashboard</a> 
                <span class="divider">/</span>
                <a href="{{path('usuarios')}}" class="bread-current">Usuarios</a>
                <span class="divider">/</span> 
                <a href="{{path('usuarios_edit',{'id':entity.id})}}" class="bread-current">Editar registro</a>
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- Page heading ends -->

        <!-- Matter -->
        <div class="matter">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="widget">

                            <div class="widget-head">
                                <div class="pull-left">Editar usuario "{{entity.name}}"</div>
                                <div class="clearfix"></div>
                            </div>

                            <div class="widget-content">
                                <div class="padd contenido-formulario">
                                    {{ form(form) }}
                                </div>
                            </div>
                            <div class="widget-foot">
                                <button id="botonRegresar" class="btn btn-default">Regresar</button>
                                <button id="botonGuardar" class="btn btn-primary">Guardar cambios</button>
                                <div style="float: left; margin-right: 3px;">
                                   <form id="formEliminar" action="{{ path('usuarios_delete', { 'id': entity.id }) }}" method="post">
                                   {{ form_widget(delete_form) }}
                                   </form>
                                   <button class="btn btn-danger " onclick="eliminarRegistro();">Eliminar</button>
                                </div>        
                            </div>
                        </div>  

                    </div>
                </div>
            </div>
        </div>
        <!-- Matter ends -->
    </div>
    <!-- Mainbar ends -->           
    <div class="clearfix"></div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script src="{{asset('js/jquery-ui-1.9.2.custom.min.js')}}"></script> <!-- jQuery UI -->
    <!-- jQuery Notification - Noty -->
    <script src="{{asset('js/jquery.noty.js')}}"></script> <!-- jQuery Notify -->
    <script src="{{asset('js/themes/default.js')}}"></script> <!-- jQuery Notify -->
    <script src="{{asset('js/layouts/bottom.js')}}"></script> <!-- jQuery Notify -->
    <script src="{{asset('js/layouts/topRight.js')}}"></script> <!-- jQuery Notify -->
    <script src="{{asset('js/layouts/top.js')}}"></script> <!-- jQuery Notify -->
    <!-- jQuery Notification ends -->
    <script src="{{asset('js/jquery.cleditor.min.js')}}"></script> <!-- CLEditor -->
    <script src="{{asset('js/languages/jquery.validationEngine-es.js')}}"></script> <!-- jQuery Validation Engine Language File -->
    <script src="{{asset('js/jquery.validationEngine.js')}}"></script> <!-- jQuery Validation Engine -->
    <script src="{{asset('js/jquery.slimscroll.min.js')}}"></script> <!-- jQuery SlimScroll -->
    <script src="{{asset('js/bootbox.min.js')}}"></script> <!-- Filter for support page -->
    <script src="{{asset('js/jquery.gritter.min.js')}}"></script> <!-- jQuery Gritter -->
    <script src="{{asset('js/custom.js')}}"></script> <!-- Custom codes -->


    <script>
        var eliminarRegistro = function(){
            {% if is_granted('ROLE_ADMIN') %}
              bootbox.confirm("Esta seguro de eliminar el registro?", function(result) {
                if(result){
                   $("#formEliminar").submit();
                }
              });
            {% else %}
              noty({text: 'No tienes los permisos suficientes para realizar esta accion',layout:'bottom', type:'warning', timeout:2000 });
            {% endif %}      
        };
        $(document).ready(function () {
            $(".validate").validationEngine();

            $("#botonRegresar").on("click", function () {
                {% if app.session.has('return') and app.session.get('return') | length > 0 %}
                    location.href = "{{app.session.get('return')}}";
                {% else %}
                    location.href = "{{path('usuarios')}}";
                {% endif %}
            });

            $("#botonGuardar").on("click", function () {
                $(".contenido-formulario form").submit();
            });
            
        /* CL Editor */
        $(".cleditor").cleditor({
            width: "auto",
            height: "auto"
        });

        {% if errores | length > 0 %}
            {% for error in errores %}
                noty({
                    text: '{{ error }}',
                    layout: 'topRight',
                    type: 'error',
                    timeout: 2000
                });
            {% endfor %}    
        {% endif %}

          });
    </script>

{% endblock %}

src/InteractiveValley/BackendBundle/Resources/views/Usuario/index.html.twig
{% extends 'BackendBundle::layout.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
    <!-- Datatables -->
    <link rel="stylesheet" href="{{asset('js/datatables/css/dataTables.bootstrap.css')}}">
    <!-- Main stylesheet -->
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <!-- Widgets stylesheet -->
    <link rel="stylesheet" href="{{asset('css/widgets.css')}}">   
    <!-- Gritter Notifications stylesheet -->
    <link rel="stylesheet" href="{{asset('css/jquery.gritter.css')}}"> 
{% endblock %}

{% block mainbar %}
    <!-- Main bar -->
    <div class="mainbar">
        <!-- Page heading -->
        <div class="page-head">
            <h2 class="pull-left">Usuarios</h2>
            <div class="clearfix"></div>
            <!-- Breadcrumb -->
            <div class="bread-crumb">
                <a href="{{path('backend_homepage')}}"><i class="fa fa-home"></i>Dashboard</a> 
                  <span class="divider">/</span>  
                  <a href="{{path('usuarios')}}" class="bread-current">Usuarios</a>
                  <a href="{{path('usuarios_new')}}" class="btn btn-info pull-right" style="color: white; margin-left: 5px;">Crear registro</a>
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- Page heading ends -->
        <!-- Matter -->
        <div class="matter">
            <div class="container">
            <!-- Table -->
                <div class="row">
                <div class="col-md-12">
                    <div class="widget">
                        <div class="widget-head">
                            <div class="pull-left">Registro de usuarios</div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="widget-content">
                            {% include 'BackendBundle:Usuario:table.html.twig' with { 'entities': entities } %}
                        </div>
                        <div class="widget-foot">
                                <br/>
                                <br/>
                                <div class="clearfix"></div>
                        </div>        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Matter ends -->
    </div>
    <!-- Mainbar ends -->        
    <div class="clearfix"></div>
{% endblock %}

{% block javascripts %}
{{ parent() }}

<script src="{{asset('js/jquery-ui-1.9.2.custom.min.js')}}"></script> <!-- jQuery UI -->
<!-- jQuery Notification - Noty -->
<script src="{{asset('js/jquery.noty.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/themes/default.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/bottom.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/topRight.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/top.js')}}"></script> <!-- jQuery Notify -->
<!-- jQuery Notification ends -->

<script src="{{asset('js/datatables/js/jquery.dataTables.js')}}"></script>
<script src="{{asset('js/jquery.slimscroll.min.js')}}"></script> <!-- jQuery SlimScroll -->

<script src="{{asset('js/bootbox.min.js')}}"></script> <!-- Filter for support page -->
<script src="{{asset('js/custom.js')}}"></script> <!-- Custom codes -->

<script>
    var editarRegistro = function (url) {
        location.href = url;
    };

    var eliminarRegistro = function () {
    {% if is_granted('ROLE_ADMIN') %}
          bootbox.confirm("Esta seguro de eliminar el registro?", function (result) {
              if (result) {
                  $("#formEliminar").submit();
              }
          });
    {% else %}
          noty({text: 'No tienes los permisos suficientes para realizar esta accion', layout: 'bottom', type: 'warning', timeout: 2000});
    {% endif %}      
    };
    
    $(document).ready(function () {
          $('#datatable').dataTable({
              "sPaginationType": "full_numbers",
              "sNext": "Siguiente",
              "sLast": "Ultimo",
              "sFirst": "Primero",
              "sPrevious": "Anterior",
          });
    });
      
</script>


{% endblock %}

src/InteractiveValley/BackendBundle/Resources/views/Usuario/show.html.twig
{% extends 'BackendBundle::layout.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
  <!-- Main stylesheet -->
  <link rel="stylesheet" href="{{asset('css/style.css')}}">
  <!-- Widgets stylesheet -->
  <link rel="stylesheet" href="{{asset('css/widgets.css')}}">   
    <!-- Gritter Notifications stylesheet -->
  <link rel="stylesheet" href="{{asset('css/jquery.gritter.css')}}"> 

{% endblock %}

{% block mainbar %}
    <!-- Main bar -->
    <div class="mainbar">

        <!-- Page heading -->
        <div class="page-head">
            <h2 class="pull-left">Usuarios</h2>
            <div class="clearfix"></div>
            <!-- Breadcrumb -->
            <div class="bread-crumb">
                <a href="{{path('backend_homepage')}}"><i class="fa fa-home"></i>Dashboard</a> 
                <span class="divider">/</span>
                <a href="{{path('usuarios')}}" class="bread-current">Usuarios</a>
                <span class="divider">/</span>
                <a href="{{path('usuarios_show',{'id': entity.id})}}" class="bread-current">{{entity.name}}</a>
                {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{path('usuarios_new')}}" class="btn btn-info pull-right" style="color: white; margin-left: 5px;">Crear registro</a>
                {% endif %}
            </div>

            <div class="clearfix"></div>

        </div>
        <!-- Page heading ends -->

        <!-- Matter -->

        <div class="matter">
            <div class="container" id="contenidoPagina">
                <div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="widget">
                                <div class="widget-head">
                                    <div class="pull-left">Registro del usuario "{{entity.name}}"</div>
                                    <div class="clearfix"></div>
                                </div>

                                <div class="widget-content">
                                    <div class="padd contenido-formulario">    
                                        <table class="record_properties">
                                            <tbody>
                                                <tr>
                                                    <th>Id</th>
                                                    <td>{{ entity.id }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Nombre</th>
                                                    <td>{{ entity.name }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Email</th>
                                                    <td>{{ entity.email }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Es activo?</th>
                                                    <td>{{ (entity.isActive)?'Si':'No' }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Tipo</th>
                                                    <td>{{ entity.stringTypeGroup }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Creado</th>
                                                    <td>{{ entity.createdAt | date('d-m-Y') }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Actualizado</th>
                                                    <td>{{ entity.updatedAt | date('d-m-Y') }}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="widget-foot">
                                    <button id="botonRegresar" class="btn btn-default" onclick="javascript:regresar('{{path('usuarios')}}')">Regresar</button>
                                    <button id="botonEditar" class="btn btn-info" onclick="javascript:editarRegistro('{{path('usuarios_edit',{id: entity.id})}}')">Editar</button>
                                    <div style="float: left; margin-right: 3px;">
                                        <form id="formEliminar" action="{{ path('usuarios_delete', { 'id': entity.id }) }}" method="post">
                                            <input name="_method" value="DELETE" type="hidden"/>
											{{ form_widget(delete_form) }}
                                        </form>
                                        <button class="btn btn-danger " onclick="eliminarRegistro();">Eliminar</button>
                                    </div>        
                                </div>
                            </div>  
                        </div>    
                    </div>
                </div>
            </div>
        </div>

        <!-- Matter ends -->

    </div>

    <!-- Mainbar ends -->        
    <div class="clearfix"></div>

{% endblock %}

{% block javascripts %}
  {{ parent() }}

<script src="{{asset('js/jquery-ui-1.9.2.custom.min.js')}}"></script> <!-- jQuery UI -->
<!-- jQuery Notification - Noty -->
<script src="{{asset('js/jquery.noty.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/themes/default.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/bottom.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/topRight.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/top.js')}}"></script> <!-- jQuery Notify -->
<!-- jQuery Notification ends -->

<script src="{{asset('js/datatables/js/jquery.dataTables.js')}}"></script>

<script src="{{asset('js/jquery.slimscroll.min.js')}}"></script> <!-- jQuery SlimScroll -->
<script src="{{asset('js/bootbox.min.js')}}"></script> <!-- Filter for support page -->
<script src="{{asset('js/custom.js')}}"></script> <!-- Custom codes -->


<script>
var regresar = function(url){
    location.href=url;
};

var editarRegistro = function(url){
    location.href=url;
};
    
var eliminarRegistro = function(){
  {% if is_granted('ROLE_ADMIN') %}
    bootbox.confirm("Esta seguro de eliminar el registro?", function(result) {
      if(result){
         $("#formEliminar").submit();
      }
    });
  {% else %}
    noty({text: 'No tienes los permisos suficientes para realizar esta accion',layout:'bottom', type:'warning', timeout:2000 });
  {% endif %}      
};

</script>

    
{% endblock %}

src/InteractiveValley/BackendBundle/Resources/views/Usuario/table.html.twig
<table id="datatable" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Email</th>
            <th>Es Activo?</th>
            <th>Tipo</th>
            <th>Fecha creacion</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody id="cuerpoTabla">
        {% for entity in entities %}
            <tr id="registro-{{entity.id}}">
                <td><a href="{{ path('usuarios_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                <td>{{ entity.name }}</td>
                <td>{{ entity.email }}</td>
                <td>{{ entity.isActive | isActive | raw }}</td>
                <td>{{ entity.stringTypeGroup }}</td>
                <td>{{ entity.createdAt | date('d/m/Y') }}</td>
                <td>
                    <button onclick="javascript:editarRegistro('{{ path('usuarios_edit', { 'id': entity.id }) }}')" class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> </button>
                    <button onclick="javascript:editarRegistro('{{ path('usuarios_show', { 'id': entity.id }) }}', '#registro-{{entity.id}}')" class="btn btn-xs btn-info"><i class="fa fa-folder-open"></i> </button>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>