src/InteractiveValley/PublicacionesBundle/Entity/Publicacion.php
<?php

namespace InteractiveValley\PublicacionesBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Publicacion
 *
 * @ORM\Table(name="publications")
 * @ORM\Entity(repositoryClass="InteractiveValley\PublicacionesBundle\Entity\PublicacionRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Publicacion
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     * @Assert\NotBlank(message="Ingresa el titulo de la publicacion")
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="slug", type="string", length=255)
     */
    private $slug;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     * @Assert\NotBlank(message="Ingresa la descripcion de la publicacion")
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="resume", type="text")
     * @Assert\NotBlank(message="Escribe el breve resumen de la publicacion")
     */
    private $resume;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @var integer
     *
     * @ORM\Column(name="contComments", type="integer")
     */
    private $contComments = 0;

    /**
     * @var integer
     *
     * @ORM\Column(name="contLikes", type="integer")
     */
    private $contLikes =  0;

    /**
     * @var integer
     *
     * @ORM\Column(name="contTwits", type="integer")
     */
    private $contTwits = 0;

    /**
     * @var integer
     *
     * @ORM\Column(name="contViews", type="integer")
     */
    private $contViews = 0;
    
    /**
     * @var string
     *
     * @ORM\Column(name="referencia", type="string", length=255,nullable=true)
     */
    private $referencia;

    /**
     * @var integer
     *
     * @ORM\Column(name="position", type="integer")
     */
    private $position = 0;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_active", type="boolean", nullable=true)
     */
    private $isActive;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @var integer
     *
     * @var InteractiveValley\PublicacionesBundle\Entity\Categoria
     * @todo Usuario validador del envio
     *
     * @ORM\ManyToOne(targetEntity="Categoria", inversedBy="publications")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="categorie_id", referencedColumnName="id")
     * })
     */
    private $categorie;

    /**
     * @var InteractiveValley\BackendBundle\Entity\Usuario
     * @todo Usuario validador del envio
     *
     * @ORM\ManyToOne(targetEntity="InteractiveValley\BackendBundle\Entity\Usuario", inversedBy="publications")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="author_id", referencedColumnName="id")
     * })
     */
    private $author;
    
    const STATUS_EN_PROCESO  =   1;
    const STATUS_REVISAR     =   2;
    const STATUS_POSTEADO    =   3;
    
    /**
     * @var integer
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status = 0;
    
    public function __construct() {
        $this->status = self::STATUS_EN_PROCESO;
        $this->isActive = false;
    }
    
    /*
     * Timestable
     */
    
    /**
     ** @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        if(!$this->getCreatedAt())
        {
            $this->createdAt = new \DateTime();
        }
        if(!$this->getUpdatedAt())
        {
            $this->updatedAt = new \DateTime();
        }
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTime();
    }
    
    /*** uploads ***/
    
    /**
     * @Assert\File(maxSize="6000000")
     */
    private $file;

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
        // check if we have an old image path
        if (isset($this->image)) {
            // store the old name to delete after the update
            $this->temp = $this->image;
            $this->image = null;
        } else {
            $this->image = 'initial';
        }
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }
    
    /**
    * @ORM\PrePersist
    * @ORM\PreUpdate
    */
    public function preUpload()
    {
      if (null !== $this->getFile()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->image = $filename.'.'.$this->getFile()->guessExtension();
        }
    }

    /**
    * @ORM\PostPersist
    * @ORM\PostUpdate
    */
    public function upload()
    {
      if (null === $this->getFile()) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move($this->getUploadRootDir(), $this->image);

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            unlink($this->getUploadRootDir().'/'.$this->temp);
            // clear the temp image path
            $this->temp = null;
        }
        $this->file = null;
    }

    /**
    * @ORM\PostRemove
    */
    public function removeUpload()
    {
      if ($file = $this->getAbsolutePath()) {
        if(file_exists($file)){
            unlink($file);
        }
      }
    }
    
    protected function getUploadDir()
    {
        return '/uploads/publicaciones';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web'.$this->getUploadDir();
    }
    
    public function getWebPath()
    {
        return null === $this->image ? null : $this->getUploadDir().'/'.$this->image;
    }
    
    public function getAbsolutePath()
    {
        return null === $this->image ? null : $this->getUploadRootDir().'/'.$this->image;
    }
    
    // custom functions
    
    public function getIsEnProceso(){
        return ($this->getStatus()==self::STATUS_EN_PROCESO);
    }
    
    public function getIsPosteada(){
        return ($this->getStatus()==self::STATUS_POSTEADO) && ($this->isActive);
    }
    
    public function getIsRevisar(){
        return ($this->getStatus()==self::STATUS_REVISAR) && ($this->isActive==false);
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Publicacion
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Publicacion
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Publicacion
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set resume
     *
     * @param string $resume
     * @return Publicacion
     */
    public function setResume($resume)
    {
        $this->resume = $resume;

        return $this;
    }

    /**
     * Get resume
     *
     * @return string 
     */
    public function getResume()
    {
        return $this->resume;
    }

    /**
     * Set image
     *
     * @param string $image
     * @return Publicacion
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string 
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set contComments
     *
     * @param integer $contComments
     * @return Publicacion
     */
    public function setContComments($contComments)
    {
        $this->contComments = $contComments;

        return $this;
    }

    /**
     * Get contComments
     *
     * @return integer 
     */
    public function getContComments()
    {
        return $this->contComments;
    }

    /**
     * Set contLikes
     *
     * @param integer $contLikes
     * @return Publicacion
     */
    public function setContLikes($contLikes)
    {
        $this->contLikes = $contLikes;

        return $this;
    }

    /**
     * Get contLikes
     *
     * @return integer 
     */
    public function getContLikes()
    {
        return $this->contLikes;
    }

    /**
     * Set contTwits
     *
     * @param integer $contTwits
     * @return Publicacion
     */
    public function setContTwits($contTwits)
    {
        $this->contTwits = $contTwits;

        return $this;
    }

    /**
     * Get contTwits
     *

src/InteractiveValley/PublicacionesBundle/Form/PublicacionType.php
<?php

namespace InteractiveValley\PublicacionesBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Doctrine\ORM\EntityRepository;
use InteractiveValley\BackendBundle\Form\DataTransformer\UsuarioToNumberTransformer;

class PublicacionType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $em = $options['em'];
        $usuarioTransformer = new UsuarioToNumberTransformer($em);
        
        $builder
            ->add('title','text',array('label'=>'Titulo','attr'=>array('class'=>'form-control')))
            ->add('slug','hidden')
            ->add('resume',null,array(
                'label'=>'Resumen',
                'required'=>true,
                'attr'=>array(
                    'class'=>'resume form-control placeholder',
                   'data-theme' => 'advanced',
                    )
                ))
            ->add('description',null,array(
                'label'=>'Contenido',
                'required'=>true,
                'attr'=>array(
                    'class'=>'description form-control placeholder',
                   'data-theme' => 'advanced',
                    )
                ))
            ->add('file','file',array('label'=>'Portada','attr'=>array('class'=>'form-control')))
            ->add('contComments','hidden')
            ->add('contLikes','hidden')
            ->add('contTwits','hidden')
            ->add('contViews','hidden')
            ->add('position','hidden')
            ->add('status','hidden')
            ->add('isActive',null,array('label'=>'Activo?','attr'=>array(
                'class'=>'checkbox-inline',
                'placeholder'=>'Es activo',
                'data-bind'=>'value: isActive'
                )))
            ->add('categorie','entity',array(
                'class'=> 'PublicacionesBundle:Categoria',
                'label'=>'Categoria',
                'required'=>true,
                'read_only'=>false,
                'choice_label'=>'name',
                'query_builder' => function(EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.name', 'ASC');
                },
                'attr'=>array(
                    'class'=>'form-control placeholder',
                    'placeholder'=>'Categoria',
                    'data-bind'=>'value: categoria',
                    )
                ))
            ->add('referencia','text',array('label'=>'Fuente/Referencia','attr'=>array('class'=>'form-control')))
            ->add($builder->create('author', 'hidden')->addModelTransformer($usuarioTransformer))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'InteractiveValley\PublicacionesBundle\Entity\Publicacion'
        ))
        ->setRequired(array('em'))
        ->setAllowedTypes(array('em' => 'Doctrine\Common\Persistence\ObjectManager'))
        ;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'interactivevalley_publicacionesbundle_publicacion';
    }
}

src/InteractiveValley/PublicacionesBundle/Resources/views/Publicacion/index.html.twig
{% extends 'BackendBundle::layout.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
    <!-- Datatables -->
    <link rel="stylesheet" href="{{asset('js/datatables/css/dataTables.bootstrap.css')}}">
    <!-- Main stylesheet -->
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <!-- Widgets stylesheet -->
    <link rel="stylesheet" href="{{asset('css/widgets.css')}}">   
    <!-- Gritter Notifications stylesheet -->
    <link rel="stylesheet" href="{{asset('css/jquery.gritter.css')}}"> 
{% endblock %}

{% block mainbar %}
    <!-- Main bar -->
    <div class="mainbar">
        <!-- Page heading -->
        <div class="page-head">
            <h2 class="pull-left">Publicaciones</h2>
            <div class="clearfix"></div>
            <!-- Breadcrumb -->
            <div class="bread-crumb">
                <a href="{{path('backend_homepage')}}"><i class="fa fa-home"></i>Dashboard</a> 
                  <span class="divider">/</span>  
                  <a href="{{path('publicaciones')}}" class="bread-current">Publicaciones</a>
                  <a href="{{path('publicaciones_new')}}" class="btn btn-info pull-right" style="color: white; margin-left: 5px;">Crear registro</a>
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- Page heading ends -->
        <!-- Matter -->
        <div class="matter">
            <div class="container">
            <!-- Table -->
                <div class="row">
                <div class="col-md-12">
                    <div class="widget">
                        <div class="widget-head">
                            <div class="pull-left">Registro de publicaciones</div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="widget-content">
                            {% include 'PublicacionesBundle:Publicacion:table.html.twig' with { 'entities': entities } %}
                        </div>
                        <div class="widget-foot">
                                <br/>
                                <br/>
                                <div class="clearfix"></div>
                        </div>        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Matter ends -->
    </div>
    <!-- Mainbar ends -->        
    <div class="clearfix"></div>
{% endblock %}

{% block javascripts %}
{{ parent() }}

<script src="{{asset('js/jquery-ui-1.9.2.custom.min.js')}}"></script> <!-- jQuery UI -->
<!-- jQuery Notification - Noty -->
<script src="{{asset('js/jquery.noty.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/themes/default.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/bottom.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/topRight.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/top.js')}}"></script> <!-- jQuery Notify -->
<!-- jQuery Notification ends -->

<script src="{{asset('js/datatables/js/jquery.dataTables.js')}}"></script>
<script src="{{asset('js/jquery.slimscroll.min.js')}}"></script> <!-- jQuery SlimScroll -->

<script src="{{asset('js/bootbox.min.js')}}"></script> <!-- Filter for support page -->
<script src="{{asset('js/custom.js')}}"></script> <!-- Custom codes -->

<script>
    var editarRegistro = function (url) {
        location.href = url;
    };

    var eliminarRegistro = function () {
    {% if is_granted('ROLE_ADMIN') %}
          bootbox.confirm("Esta seguro de eliminar el registro?", function (result) {
              if (result) {
                  $("#formEliminar").submit();
              }
          });
    {% else %}
          noty({text: 'No tienes los permisos suficientes para realizar esta accion', layout: 'bottom', type: 'warning', timeout: 2000});
    {% endif %}      
    };
    
    $(document).ready(function () {
          $('#datatable').dataTable({
              "aaSorting": [[0,'desc']],
              "sPaginationType": "full_numbers",
              "sNext": "Siguiente",
              "sLast": "Ultimo",
              "sFirst": "Primero",
              "sPrevious": "Anterior",
          });
    });
    function backend(id,clase){
        $(".loader").fadeIn();
        var $registro = $("#registro-"+id);
        var url = $registro.find(clase).data('url');
        //alert(url);
        $.ajax({
            url: url,
            type: 'PATCH',
            dataType: 'html',
            success: function(data){
                $registro.html($(data).html());
                notySuccess('Actualizacion realizada');
                $(".loader").fadeOut();
            },
            error: function(data){
                notyError('Error de actualizacion');
                console.log(data);
                $(".loader").fadeOut();
            },
        });
    }  
</script>


{% endblock %}

src/InteractiveValley/PublicacionesBundle/Resources/views/Publicacion/item.html.twig
<tr id="registro-{{entity.id}}">
    <td><a href="{{ path('publicaciones_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
    <td>
        {% if entity.image | length > 0 %}
            <img src="{{ entity.webPath }}" style="max-width: 120px; max-width: 120px;"/>
        {% else %}    
            sin imagen
        {% endif %}
    </td>
    <td>{{ entity.title }}</td>
    <td>{{ entity.resume | raw }}</td>
    <td>
        <ul class="list-info-publicacion">
            <li class="item-info-publicacion">Activo?: {{ entity.isActive | isActive | raw }}</li>
            <li class="item-info-publicacion">Creado: {{ entity.createdAt | date('d/m/Y G:ia') }}</li>
            <li class="item-info-publicacion">Author: {{ entity.author.name }}</li>
            <li class="item-info-publicacion">Views: {{ entity.contViews }}</li>
        </ul>
    </td>
    <td>{{ entity.status | status | raw }}</td>
    <td>
        <button onclick="javascript:editarRegistro('{{ path('publicaciones_edit', { 'id': entity.id }) }}')" class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> </button>
        <button onclick="javascript:editarRegistro('{{ path('publicaciones_show', { 'id': entity.id }) }}', '#registro-{{entity.id}}')" class="btn btn-xs btn-info"><i class="fa fa-folder-open"></i> </button>
        <a href="{{ path('publicacion', { 'slug': entity.slug,'no-count':'1','debug':'1' }) }}" target="_blank" class="btn btn-xs btn-warning"><i class="fa fa-eye"></i> </a>
        {% if entity.isEnProceso %}
            <button data-url="{{path('publicaciones_revisar', { 'id': entity.id }) }}" onclick="javascript:backend({{entity.id}}, '.revisar')" class="btn btn-xs btn-danger revisar"><i class="fa fa-frown-o"></i></button>
            <button data-url="{{path('publicaciones_publicar', { 'id': entity.id }) }}" onclick="javascript:backend({{entity.id}}, '.publicar')" class="btn btn-xs btn-success publicar"><i class="fa fa-check"></i></button>
        {% elseif entity.isRevisar %}
            <button data-url="{{path('publicaciones_publicar', { 'id': entity.id }) }}" onclick="javascript:backend({{entity.id}}, '.publicar')" class="btn btn-xs btn-success publicar"><i class="fa fa-check"></i></button>
        {% elseif entity.isPosteada %}
            <button data-url="{{path('publicaciones_revisar', { 'id': entity.id }) }}" onclick="javascript:backend({{entity.id}}, '.revisar')" class="btn btn-xs btn-danger revisar"><i class="fa fa-frown-o"></i></button>
        {% endif %}
    </td>
</tr>

src/InteractiveValley/PublicacionesBundle/Resources/views/Publicacion/show.html.twig
{% extends 'BackendBundle::layout.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
  <!-- Main stylesheet -->
  <link rel="stylesheet" href="{{asset('css/style.css')}}">
  <!-- Widgets stylesheet -->
  <link rel="stylesheet" href="{{asset('css/widgets.css')}}">   
    <!-- Gritter Notifications stylesheet -->
  <link rel="stylesheet" href="{{asset('css/jquery.gritter.css')}}"> 

{% endblock %}

{% block mainbar %}
    <!-- Main bar -->
    <div class="mainbar">

        <!-- Page heading -->
        <div class="page-head">
            <h2 class="pull-left">Publicaciones</h2>
            <div class="clearfix"></div>
            <!-- Breadcrumb -->
            <div class="bread-crumb">
                <a href="{{path('backend_homepage')}}"><i class="fa fa-home"></i>Dashboard</a> 
                <span class="divider">/</span>
                <a href="{{path('publicaciones')}}" class="bread-current">Publicaciones</a>
                <span class="divider">/</span>
                <a href="{{path('publicaciones_show',{'id': entity.id})}}" class="bread-current">{{entity.title}}</a>
                {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{path('publicaciones_new')}}" class="btn btn-info pull-right" style="color: white; margin-left: 5px;">Crear registro</a>
                {% endif %}
            </div>

            <div class="clearfix"></div>

        </div>
        <!-- Page heading ends -->

        <!-- Matter -->

        <div class="matter">
            <div class="container" id="contenidoPagina">
                <div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="widget">
                                <div class="widget-head">
                                    <div class="pull-left">Publicación:  "{{entity.title}}"</div>
                                    <div class="clearfix"></div>
                                </div>

                                <div class="widget-content">
                                    <div class="padd contenido-formulario">    
                                        <table class="record_properties">
                                            <tbody>
                                                <tr>
                                                    <th>Id</th>
                                                    <td>{{ entity.id }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Titulo</th>
                                                    <td>{{ entity.title }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Resumen</th>
                                                    <td>{{ entity.resume | raw }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Descripcion</th>
                                                    <td>{{ entity.description | raw }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Imagen</th>
                                                    <td>
                                                        {% if entity.image | length > 0 %}
                                                            <img src="{{ entity.webPath }}" style="max-width: 400px; max-width: 600px;"/>
                                                        {% else %}    
                                                            sin imagen
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <th>Fuente/Referencia</th>
                                                    <td>{{ entity.referencia }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Es activa?</th>
                                                    <td>{{ (entity.isActive)?'Si':'No' }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Creado</th>
                                                    <td>{{ entity.createdAt | date('d-m-Y') }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Actualizado</th>
                                                    <td>{{ entity.updatedAt | date('d-m-Y') }}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="widget-foot">
                                    <button id="botonRegresar" class="btn btn-default" onclick="javascript:regresar('{{path('publicaciones')}}')">Regresar</button>
                                    <button id="botonEditar" class="btn btn-info" onclick="javascript:editarRegistro('{{path('publicaciones_edit',{id: entity.id})}}')">Editar</button>
                                    <div style="float: left; margin-right: 3px;">
                                        <form id="formEliminar" action="{{ path('publicaciones_delete', { 'id': entity.id }) }}" method="post">
                                            <input name="_method" value="DELETE" type="hidden"/>
											{{ form_widget(delete_form) }}
                                        </form>
                                        <button class="btn btn-danger " onclick="eliminarRegistro();">Eliminar</button>
                                    </div>        
                                </div>
                            </div>  
                        </div>    
                    </div>
                </div>
            </div>
        </div>

        <!-- Matter ends -->

    </div>

    <!-- Mainbar ends -->        
    <div class="clearfix"></div>

{% endblock %}

{% block javascripts %}
  {{ parent() }}

<script src="{{asset('js/jquery-ui-1.9.2.custom.min.js')}}"></script> <!-- jQuery UI -->
<!-- jQuery Notification - Noty -->
<script src="{{asset('js/jquery.noty.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/themes/default.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/bottom.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/topRight.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/top.js')}}"></script> <!-- jQuery Notify -->
<!-- jQuery Notification ends -->

<script src="{{asset('js/datatables/js/jquery.dataTables.js')}}"></script>

<script src="{{asset('js/jquery.slimscroll.min.js')}}"></script> <!-- jQuery SlimScroll -->
<script src="{{asset('js/bootbox.min.js')}}"></script> <!-- Filter for support page -->
<script src="{{asset('js/custom.js')}}"></script> <!-- Custom codes -->


<script>
var regresar = function(url){
    location.href=url;
};

var editarRegistro = function(url){
    location.href=url;
};
    
var eliminarRegistro = function(){
  {% if is_granted('ROLE_ADMIN') %}
    bootbox.confirm("Esta seguro de eliminar el registro?", function(result) {
      if(result){
         $("#formEliminar").submit();
      }
    });
  {% else %}
    noty({text: 'No tienes los permisos suficientes para realizar esta accion',layout:'bottom', type:'warning', timeout:2000 });
  {% endif %}      
};

</script>

    
{% endblock %}

src/InteractiveValley/PublicacionesBundle/Resources/views/Publicacion/table.html.twig
<table id="datatable" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Portada</th>
            <th>Titulo</th>
            <th>Resumen</th>
            <th>Información</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody id="cuerpoTabla">
        {% for entity in entities %}
            {% include 'PublicacionesBundle:Publicacion:item.html.twig' with { 'entity': entity } %}
        {% endfor %}
    </tbody>
</table>